INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('John Doe', '123-456-7890', 'Papagaio', 'Rua A', 'Industrial', 'Aracaju', '2022-07-28', 'Saudavel', 'Soltura');

INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Maria Silva', '987-654-3210', 'Galo dgua', 'Rua B', 'Centro', 'São Paulo', '2022-09-15', 'Ferido', 'Clínica Veterinária');

INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Carlos Souza', '456-789-1230', 'Jabuti', 'Rua C', 'Jardins', 'Belo Horizonte', '2023-02-10', 'Doente', 'Adoção');

INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Ana Pereira', '321-654-9870', 'Tartaruga', 'Rua D', 'Morumbi', 'Rio de Janeiro', '2023-05-22', 'Saudavel', 'Reabilitação');

INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('João Silva', '987-654-3210', 'Cachorro', 'Rua E', 'Centro', 'São Paulo', '2023-05-10', 'Ferido', 'Clínica Veterinária');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Maria Souza', '123-456-7890', 'Gato', 'Rua F', 'Copacabana', 'Rio de Janeiro', '2023-05-15', 'Abandonado', 'Adoção');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Carlos Andrade', '456-123-7890', 'Pomba', 'Rua G', 'Centro', 'Salvador', '2023-05-18', 'Doente', 'Reabilitação');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Fernanda Lima', '654-321-9870', 'Cavalo', 'Estrada Rural', 'Fazenda', 'Belo Horizonte', '2023-05-22', 'Saudável', 'Retorno ao Local');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Lucas Carvalho', '321-654-0987', 'Jacaré', 'Rua H', 'Jardim', 'Manaus', '2023-05-28', 'Agressivo', 'Reserva Ambiental');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Paula Medeiros', '987-321-6540', 'Cervo', 'Rua I', 'Bosque', 'Curitiba', '2023-06-05', 'Saudável', 'Reabilitação');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Renato Alves', '654-789-1230', 'Capivara', 'Rua J', 'Ribeirinho', 'Porto Alegre', '2023-06-11', 'Ferido', 'Clínica Veterinária');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Camila Nogueira', '456-789-1230', 'Lobo', 'Rua K', 'Montanha', 'Brasília', '2023-06-17', 'Agressivo', 'Reserva Ambiental');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Victor Gomes', '123-789-4560', 'Onça-pintada', 'Estrada Z', 'Floresta', 'Florianópolis', '2023-06-22', 'Saudável', 'Reabilitação');
INSERT INTO tb_resgate (applicant, phone_applicant, specie, address, neighborhood, city, data, animal_situation, animal_destination) VALUES ('Juliana Santos', '789-123-4560', 'Tucano', 'Rua L', 'Parque', 'Fortaleza', '2023-06-29', 'Doente', 'Adoção');
